// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// OnNotify provides a mock function with given fields: notification
func (_m *Observer) OnNotify(notification string) {
	_m.Called(notification)
}
