// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	activityreporter "git.garena.com/sea-labs-id/bootcamp/batch-03/tsanaativa-vinnera/assignment-activity-reporter/activityreporter"
	mock "github.com/stretchr/testify/mock"
)

// Subject is an autogenerated mock type for the Subject type
type Subject struct {
	mock.Mock
}

// Notify provides a mock function with given fields: notification
func (_m *Subject) Notify(notification string) {
	_m.Called(notification)
}

// Register provides a mock function with given fields: observer
func (_m *Subject) Register(observer activityreporter.Observer) {
	_m.Called(observer)
}
